name: Flutter/release

on:
  create:
    tags:
      - v*

jobs:
  apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          
      - uses: subosito/flutter-action@v2
        # with:
        #   flutter-version: '3.7.7'
      - run: flutter pub get
      # - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle
      
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/output/flutter-apk/app-release.apk*"
  
  linux:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     
     - uses: subosito/flutter-action@v2
       with:
         channel: 'stable'
     - run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev
     - run: flutter config --enable-linux-desktop
     - run: flutter build linux
     
     # - uses: ncipollo/release-action@v1
     #   with:
     #    artifacts: "build/linux/x64/release/bundle"
